name: motivaciones_diarias
description: An App to give you a new motivational quote every day of year.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-19.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  share: ^2.0.4
  date_field: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/